### ISSUE TITLE
Packaging: `pyproject.toml` seems out of date; which packages are needed as tependencies for running the tests?

### ISSUE THREAD

**Issue by dreirund** [xyz2tex/svg2tikz#200]
Ahoj,

I have made an Arch Linux package from this software ("[`svg2tikz-git`](https://aur.archlinux.org/packages/svg2tikz-git)"), and while doing so there are some packaging issues I observed:

* [`pyproject.toml`](https://github.com/xyz2tex/svg2tikz/blob/master/pyproject.toml#L3) says that the version of `svg2tikz` is 3.0.1, but the version of the software in this repository is at 3.1.0.

* [Some people observe that the tests seem to need python packages that cannot be found in the source of this software using `grep -r`](https://aur.archlinux.org/packages/svg2tikz-git#comment-975720), e.g. `classpath` and `numpy`.  
  It is unclear for me where they come from and how they are needed.

  So, can you add to the [`README.md`](https://github.com/xyz2tex/svg2tikz/blob/master/README.md) a complete list of dependencies

  * for runtime,
  * for building,
  * for testing

  for the cases where `pip` is not the way to go, because the package e.g. is packaged as a distribution package?

Regards!

**Comment by ldevillez** [comment]
Hello @dreirund
Thanks for your message and for your work for creating the Arch Linux package.

I forgot to update the pyproject.toml and to publish the new version to pypi but It should be fixed now.

I don't know why `classpath` and `numpy` are inside the `poetry.lock`. Maybe because of the dependencies of the dependencies (`inkex` use `numpy for example: https://gitlab.com/inkscape/extensions/-/blob/master/pyproject.toml?ref_type=heads). 
All my directs dependencies are `lxml` and `inkex`. All the other package that the project use are standards packages. 

Normally, a description of how to test is in the doc (http://xyz2tex.github.io/svg2tikz/contribute.html#tools).

For building I just use the tools from `poetry` but I don't think it is a requirement.

Otherwise everything is specified in the [pyproject.toml](https://github.com/xyz2tex/svg2tikz/blob/master/pyproject.toml). So in that case, should I still add a list of the dependencies in the README.md (or in the docs) ?

Regards

**Comment by dreirund** [comment]
Ahoj,

> *I don't know why `classpath` and `numpy` are inside the `poetry.lock`. Maybe because of the dependencies of the dependencies (`inkex` use `numpy` for example: https://gitlab.com/inkscape/extensions/-/blob/master/pyproject.toml?ref_type=heads). All my directs dependencies are `lxml` and`inkex`. All the other package that the project use are standards packages.

OK, thanks for clarifying.

So then you and me were correct, and the issue the user faced comes from somewhere else.

> *Normally, a description of how to test is in the doc (http://xyz2tex.github.io/svg2tikz/contribute.html#tools).*

Thanks, so really there is nothing special needed.


> *Otherwise everything is specified in the [`pyproject.toml`](https://github.com/xyz2tex/svg2tikz/blob/master/pyproject.toml). So in that case, should I still add a list of the dependencies in the README.md (or in the docs) ?*

I think just a reference to the file should be enough, if that clarifies that there is nothing extra needed to build or run the tests (as you clarified in your answer).

Regards!
