### ISSUE TITLE
Add support for the symbol element

### ISSUE THREAD

**Issue by kjellmf** [xyz2tex/svg2tikz#26]
http://www.w3.org/TR/SVG/struct.html#SymbolElement
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol

**Comment by jkut** [comment]
Hi!

As far as I have seen you already implemented something regarding symbols in SVG. Unfortunately this does not work: My tests with some SVG files failed.

To compensate this problem I have written a converter in Python which will resolve all symbol usage tags in the XML tree. It directly processes the XML tree. For testing purposes I patched your code (which was pretty hard to find the right position to do that, because I do not know your code very well) so that this preprocessing will adapt the XML tree prior to your processing of the data. It is not the most elegant solution, but it works.

I would be happy to contribute: If you are interested, I can provide you with this code fragment. (And you might have a better idea how and where to integrate it into your code.) Nevertheless a more elegant solution would of course resolve these symbols during processing. Please contact me if you are interested, and I will help.

**Comment by kjellmf** [comment]
@jkut If you want to contribute that's great! Feel free to submit a pull request.

The existing SymbolElement code in svg2tikz is probably just a placeholder to remind me to implement this later. I have not worked on svg2tikz actively for a very long time, so I don't always remember whats implemented or not.

**Comment by ldevillez** [comment]
Closed by #81
