### ISSUE TITLE
error in pip install

### ISSUE THREAD

**Issue by kwyip** [xyz2tex/svg2tikz#90]
`svg2tikz 1.2.0 depends on inkex<2.0.0 and >=1.2.2+dairiki.1`
I update the `inkex`. But what is `dairiki.1`?

**Comment by ldevillez** [comment]
Hello @kwyip 

So `inkex` is the package developed by inkscape and used for their extension. 
For svg2tikz as we want to also provide a python package / cmd line tool, we also need to install `inkex`. The version on pip is an old one.

On the gitlab of inkscape someone build release for inkex but it is not an official build (https://gitlab.com/dairiki/inkex/) so that's why there is the `dairiki.1`. In the future, there should be new release on the pip package
