### ISSUE TITLE
Round corner - Error in shapes

### ISSUE THREAD

**Issue by ldevillez** [xyz2tex/svg2tikz#96]
Update: your fix did fix the error, but the output doesn't work correctly on any path with curves. The straight-line pentagon now exports correctly, but if I round the corners (as in [test.svg](https://user-images.githubusercontent.com/52675289/228267689-2dcd8c6f-c351-48ce-bd19-ff992454cc70.svg)), there's something very wrong with the shape tikz produces:

Intended shape:
![input svg](https://user-images.githubusercontent.com/52675289/228268133-842c5ae8-7d31-4dfb-b84f-c30121f2b018.JPG)

Actual shape:
![output tikz](https://user-images.githubusercontent.com/52675289/228267555-32554740-722d-4cb0-9ea8-8be3017d8184.JPG)

Here's the TikZ code generated:
`\path[fill=black,line width=0.026cm] (6.4182,11.8297) .. controls (-3.3460, 16.7118) and (3.1158, 25.4357) .. (4.7416, 14.6407) .. controls (6.3675, 25.8543) and (-3.4739, 13.8377) .. (7.2951, 12.0481) .. controls (18.0642, 19.4414) and (5.5201, 3.9865) .. (10.5499, 13.6755) .. controls (15.5796, 6.3355) and (17.6684, 9.4962) .. (10.0079, 17.2738) .. controls (2.3474, 4.6485) and (16.1824, 22.7524) .. (6.4182, 17.8703) -- cycle;`

It looks like something's wrong with the y-coordinates of the control points?

_Originally posted by @lytefoot in https://github.com/xyz2tex/svg2tikz/issues/89#issuecomment-1486989896_

**Comment by ldevillez** [comment]
I've pushed a fix on master for you to try @lytefoot :)

**Comment by lytefoot** [comment]
This works almost perfectly--you are extremely cool!

For a few svg files, Inksape gives the following error:
![error](https://user-images.githubusercontent.com/52675289/228648267-a8869227-d1a8-43a4-8553-13a3d3e5eb30.JPG)
However, even though it gives the error message, there isn't any error: it produced complete output which actually does create the image in TikZ.

As far as I can tell, the error only occurs for SVG files created with an old version of inkscape (prior to the switch from 90dpi to 96dpi), for example, this one from wikimedia commons: 
([Silhouette_of_Woman_with_Short_Hair_and_Jeans - cc0](https://user-images.githubusercontent.com/52675289/228649039-6a02dd0a-28c4-49bb-836b-6cd35f876f38.svg)). It does still happen if I re-save the SVG in the current version of inkscape.

Since the actual output works fine--the error message doesn't indicate an actual error--and it only affects a few images, this absolutely doesn't require an immediate fix.

**Comment by ldevillez** [comment]
Yeah the update of the inkscape part of the extension is still not tested nor updated.
For now, I'm working on the unitary test of the global code but this will be fixed later :)
